#include "floppysounds/floppy00.h" //reset sound
#include "floppysounds/floppy01.h"
#include "floppysounds/floppy02.h"
#include "floppysounds/floppy03.h"
#include "floppysounds/floppy04.h"
#include "floppysounds/floppy05.h"
#include "floppysounds/floppy06.h"
#include "floppysounds/floppy07.h"
#include "floppysounds/floppy08.h"
#include "floppysounds/floppy09.h"
#include "floppysounds/floppy10.h"
#include "floppysounds/floppy11.h"
#include "floppysounds/floppy12.h"
#include "floppysounds/floppy13.h"
#include "floppysounds/floppy14.h"
#include "floppysounds/floppy15.h"
#include "floppysounds/floppy16.h"
